// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock_main is a generated GoMock package.
package main

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockApiClient is a mock of ApiClient interface.
type MockApiClient struct {
	ctrl     *gomock.Controller
	recorder *MockApiClientMockRecorder
}

// MockApiClientMockRecorder is the mock recorder for MockApiClient.
type MockApiClientMockRecorder struct {
	mock *MockApiClient
}

// NewMockApiClient creates a new mock instance.
func NewMockApiClient(ctrl *gomock.Controller) *MockApiClient {
	mock := &MockApiClient{ctrl: ctrl}
	mock.recorder = &MockApiClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiClient) EXPECT() *MockApiClientMockRecorder {
	return m.recorder
}

// ApiDouble mocks base method.
func (m *MockApiClient) ApiDouble(valueToDouble int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApiDouble", valueToDouble)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApiDouble indicates an expected call of ApiDouble.
func (mr *MockApiClientMockRecorder) ApiDouble(valueToDouble interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApiDouble", reflect.TypeOf((*MockApiClient)(nil).ApiDouble), valueToDouble)
}
